name: Pulumi
on:
  pull_request:
    paths:
      - package-lock.json
      - package.json
      - pulumi.homelab.yaml
      - pulumi.yaml

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - id: pulumi-run
        uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: homelab
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
