name: Pulumi
on:
  pull_request:
    branches:
      - "**"

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2

      - id: setup-golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - id: download-modules
        run: go mod download

      - id: gcp-auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - id: pulumi-run
        uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: prod
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
