name: Pulumi
on:
  push:
    branches:
      - main
    paths:
      - package-lock.json
      - package.json
      - pulumi.homelab.yaml
      - pulumi.yaml

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - id: pulumi-run
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: prod
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
