name: Pulumi
on:
  push:
    branches:
      - main
    paths:
      - go.mod
      - go.sum
      - main.go
      - pulumi.prod.yaml
      - pulumi.yaml

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2

      - id: setupgolang
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - id: download-modules
        run: go mod download

      - id: gcp-auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - id: pulumi-run
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: prod
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
